### ISSUE TITLE
adding LIGGGHTS(R)-PUBLIC to Singularity container

### ISSUE THREAD

**Issue by LinuxPersonEC** [AndreWeiner/of_pytorch_docker#2]
This is a feature request to add [LIGGGHTS(R)-PUBLIC](https://www.cfdem.com/media/DEM/docu/Section_start.html) to the Singularity container. I'm happy to troubleshoot any steps.

**Comment by AndreWeiner** [comment]
Dear @RobbieTheK,
thanks for opening this issue. I don't see how this feature could be of general interest to OpenFOAM+ML users. Could you elaborate? If you want to use the DEM package in conjunction with OpenFOAM, feel free to extend the Dockerfile provided in this repository. If you don't need the ML part, start with the official [container](https://develop.openfoam.com/packaging/containers/-/blob/main/openfoam-docker).
Best, Andre

**Comment by LinuxPersonEC** [comment]
> Dear @RobbieTheK,
> thanks for opening this issue. I don't see how this feature could be of general interest to OpenFOAM+ML users. Could you elaborate? If you want to use the DEM package in conjunction with OpenFOAM, feel free to extend the Dockerfile provided in this repository. If you don't need the ML part, start with the official [container](https://develop.openfoam.com/packaging/containers/-/blob/main/openfoam-docker).

We have some data scientists that use them together and being on RHEL makes it difficult to get all of these working natively. We also don't use Docker for security reasons, so I thought it'd be a nice feature to have a Singularity container with the DEM package included.

**Comment by AndreWeiner** [comment]
I see. Nonetheless, I would start with an OpenFOAM-only container since the container provided here is meant to be used for CFD + machine learning applications (PyTorch). Singularity supports converting Docker into Singularity images (you don't even need Docker; Singularity allows building images from a Docker registry).
Best, Andre
