### ISSUE TITLE
How to install this environment myself instead of using docker images

### ISSUE THREAD

**Issue by jiangzhangze** [AndreWeiner/of_pytorch_docker#3]
Hi @AndreWeiner 
Thank you for your sharing.For some personal reasons.I want to install this environment in my system myself instead of using docker images.What should I do.

Best Wishes！

**Comment by AndreWeiner** [comment]
Hi @jiangzhangze,
the easiest way would be to execute the instructions in the [Dockerfile](https://github.com/AndreWeiner/of_pytorch_docker/blob/master/Dockerfile) locally on your machine. I wrote a short [article](https://ml-cfd.com/openfoam/pytorch/docker/2020/12/29/running-pytorch-models-in-openfoam.html) about the topic some time ago.
Best, Andre
