### ISSUE TITLE
Alternative Runtime: Enroot

### ISSUE THREAD

**Issue by dr-br** [AndreWeiner/of_pytorch_docker#4]
Hi Andre,
because I find it worth mentioning, I would like to point out an alternative (runtime) to Docker, Podman or Apptainer: [enroot](https://github.com/NVIDIA/enroot) by NVIDIA  
Especially when it comes to using GPUs (NVIDIA and AMD), this solution is very robust and easy to use, also on HPC-environments (e.g. [here](https://www.nhr.kit.edu/userdocs/horeka/containers/#enroot)).

Assuming, I want to use your Docker image:

```bash
enroot import docker://andreweiner/of_pytorch:of2206-py1.12.1-cpu
enroot create --name of2206-py1.12.1-cpu andreweiner+of_pytorch+of2206-py1.12.1-cpu.sqsh
enroot start -m "$PWD/test":"/home/$USER" of2206-py1.12.1-cpu bash
```

Maybe this hint is useful somehow ;)

Best regards
Samuel

**Comment by AndreWeiner** [comment]
Hi Samuel,
awesome, thank you for that inside! I haven't used enroot so far, but I'll give it try.
I'll also add a note to the README once the tests are completed.
Cheers!
Andre

**Comment by AndreWeiner** [comment]
Hi again, 
the steps you provided worked nicely, so I added some instructions to the README. I'll close this issue for now, but feel free to keep commenting if necessary.
Cheers,
Andre
